version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  qdrant:
    image: qdrant/qdrant 
    restart: unless-stopped
    ports: 
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: